apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: dependency-watchdog-prober
  name: dependency-watchdog-prober-config
  data:
    dep-config.yaml: |
      internalKubeConfigSecretName: "shoot-access-dependency-watchdog-internal-probe"
      externalKubeConfigSecretName: "shoot-access-dependency-watchdog-external-probe"
      dependentResourceInfos:
        - ref:
            kind: "Deployment"
            name: "kube-controller-manager"
            apiVersion: "apps/v1"
          shouldExist: true
          scaleUp:
            level: 0
            replicas: 1
          scaleDown:
            level: 1
        - ref:
            kind: "Deployment"
            name: "machine-controller-manager"
            apiVersion: "apps/v1"
          shouldExist: true
          scaleUp:
            level: 1
            initialDelay: 30s
            replicas: 1
          scaleDown:
            level: 0
        - ref:
            kind: "Deployment"
            name: "cluster-autoscaler"
            apiVersion: "apps/v1"
          shouldExist: false
          scaleUp:
            level: 2
            replicas: 1
          scaleDown:
            level: 0
