# Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed 
# under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file.
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true



[[constraint]]
  version = "kubernetes-1.14.2"
  name = "k8s.io/api"

[[constraint]]
  name = "k8s.io/client-go"
  version = "11.0.0"

[[override]]
  version = "kubernetes-1.14.2"
  name = "k8s.io/component-base"

[[override]]
  version = "kubernetes-1.14.2"
  name = "k8s.io/apimachinery"

[[override]]
  version = "kubernetes-1.14.2"
  name = "k8s.io/apiserver"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.14.2"

[[constraint]]
  name = "k8s.io/klog"
  version = "0.3.0"

[[override]]
  name = "k8s.io/kubernetes"
  version = "1.14.2"

[prune]
  go-tests = true
  unused-packages = true
